---
title: Dan Rader Portfolio
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
email: howdy@danrdesign.com
description: Capitol Cider House is cidery and taproom located at 3930 Georgia Avenue,
  steps from the metro in the heart of D.C.’s Petworth neighborhood. We focus on creating
  and curating craft hard cider with modern flavors.
url: https://capitolciderhouse.com
permalink: pretty
social-media-image: "/uploads/cch_OG.png"
exclude:
- node_modules
- gulpfile.js
logo: ""
