---
title: Dan Rader Portfolio
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
email: howdy@danrdesign.com
description: replace me
url: https://capitolciderhouse.com
permalink: pretty
social-media-image: ""
exclude:
- node_modules
- gulpfile.js
logo: ""
